import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { SideProvider } from "@/context/main";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
let navbar = <Navbar />;
let sidebar = <Sidebar />;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SideProvider>
          <div className="relative">
            {sidebar}
            {navbar}
            {children}
          </div>
        </SideProvider>
      </body>
    </html>
  );
}
