import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { SideProvider } from "@/context/SideContext";
import { AuthProvider } from "@/context/AuthContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbar = <Navbar />;
const sidebar = <Sidebar />;
export default function RootLayout({children,}: Readonly<{  children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SideProvider>
            <div className="relative">
              {sidebar}
              {navbar}
              {children}
            </div>
          </SideProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
